jobs:

  - name: provision
    type: runSh
    steps:
      - IN: waffle_cone_repo
        switch: off
      - IN: terraform_params
      - IN: softsrv_aws_creds
      - IN: tfState
        switch: off
      - TASK:
        - script: IN_STATE=/build/IN/tfState/state/state
        - script: if [ -f $IN_STATE/terraform.tfstate ]; then cp $IN_STATE/terraform.tfstate $WAFFLE_CONE_REPO_STATE/ ; fi
        - script: ls $IN_STATE
        - script: cd $WAFFLE_CONE_REPO_STATE
        - script: ls
        - script: terraform $TFACTION
      - OUT: tfState
    always:
      - script: echo 'save state if we created it'
      - script: OUT_STATE=/build/OUT/tfState/state/state
      - script: if [ -f $WAFFLE_CONE_REPO_STATE/terraform.tfstate ]; then cp $WAFFLE_CONE_REPO_STATE/terraform.tfstate $OUT_STATE ; fi
      - script: ls $OUT_STATE
